- name: Print plan
  run: |
    export PLAN="${{ needs.plan.outputs.manifest }}"
    export APP_VERSION="$(echo "$PLAN" | jq -r '.releases[0].app_version')"
    echo "APP_VERSION=$APP_VERSION"
    envsubst "$PLAN" > manifest.yml
    echo "manifest:"
    cat manifest.yml