- name: Print plan
  run: |
    export PLAN="${{ needs.plan.outputs.tag-flag }}"
    export APP_VERSION="$(echo "$PLAN" | jq -r '.releases[0].app_version')"
    echo "APP_VERSION=$APP_VERSION"
    envsubst < manifest.template.yml > manifest.yml
    echo "manifest:"
    cat manifest.yml