name: Generate manifest

on:
  workflow_call:

jobs:
  generate_manifest:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v4
    - name: Generate manifest
      run: |
        export VERSION=${GITHUB_REF#refs/tags/v}
        export GITHUB_REPOSITORY_NAME="${{ github.event.repository.name }}"
        export GITHUB_REPOSITORY_OWNER="${{ github.repository_owner }}"
        cat manifest.template.yml | envsubst > manifest.yml
        echo "manifest:"
        cat manifest.yml
    - name: "Upload artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-manifest
        path: |
          manifest.yml