name: Generate manifest

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  generate-manifest:
    runs-on: "ubuntu-latest"
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - name: Print plan
        run: |
          echo "$PLAN"