name: Tests and release

on:
  push:
    branches:
      - "**"
    tags:        
      - '*' 
  pull_request:

env:
  CRATE_NAME: atlas-cli-rust-plugin
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: atlas-cli-rust-plugin
            name: atlas-cli-rust-plugin-darwin_amd64.tar.gz
            command: both
          - release_for: macOS-arm64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: atlas-cli-rust-plugin
            name: atlas-cli-rust-plugin-darwin_arm64.tar.gz
            command: both

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Add Version as environment variable
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "BINARY=${{ matrix.platform.bin }}" >> $GITHUB_ENV
    
      - name: Add version to manifest file
        run: |
          # Change $VERSION in the manifest.yml to the version of the release
          envsubst < manifest.template.yml > manifest_temp.yml && mv manifest_temp.yml manifest.yml

      - name: Package as archive
        shell: bash
        run: |
            cd target/${{ matrix.platform.target }}/release
            if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
                7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }} ../../../manifest.yml
            else
                tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }} -C ../../../ manifest.yml
            fi
            cd -
        if: startsWith( github.ref, 'refs/tags/v' )
    
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: "atlas-cli-rust-plugin-*"
        if: startsWith( github.ref, 'refs/tags/v' )

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: "atlas-cli-rust-plugin-*"
        if: startsWith( github.ref, 'refs/tags/v' )